// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyAcademy1.Models;

public partial class Direction
{
    public byte DirectionId { get; set; }

    public string DirectionName { get; set; }

    public virtual ICollection<Group> Groups { get; set; } = new List<Group>();
}