// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyAcademy1.Models;

public partial class Discipline
{
    public short DisciplineId { get; set; }

    public string DisciplineName { get; set; }

    public byte NumberOfLessons { get; set; }
}