// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyAcademy1.Models;

public partial class Group
{
    public int GroupId { get; set; }

    public string GroupName { get; set; }

    public byte? Direction { get; set; }

    public virtual Direction DirectionNavigation { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}